development:
  adapter: postgresql
  database: miniproject
  pool: 5
  username: techstars
  password: 

test:
  adapter: postgresql
  database: miniproject
  pool: 5
  username: techstars
  password: 

production:
  adapter: postgresql
  database: miniproject
  pool: 5
  username: techstars
  password: 